name: test

on: [pull_request, push]

jobs:
  gh-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
      - uses: avsm/setup-ocaml@main
      - run: opam reinstall -y bisect_ppx
      - run: opam install -y --deps-only .
      - run: opam list

      - run: opam exec -- dune exec --instrument-with bisect_ppx ./simple.exe -- github

      - run: opam exec -- bisect-ppx-report send-to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}